# Generated by Django 4.2.1 on 2023-06-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_likes_alter_comment_id'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMessage',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forum.comment')),
                ('received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikeMessage',
            fields=[
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forum.like')),
                ('received', models.BooleanField(default=False)),
            ],
        ),
    ]
