# Generated by Django 4.2.1 on 2023-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lastCommented',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
